### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by li8911255** [CodingForMoney/axe#4]
Unable to find a specification for `MXReact/CxxBridge`

**Comment by CodingForMoney** [comment]
Did you setup `CocoaPods` correctly?

Maybe you should try :

`pod repo update`

**Comment by li8911255** [comment]
@CodingForMoney not working, my CocoaPods version is 1.3.1,does it have any incompatibility？

**Comment by CodingForMoney** [comment]
I don't think CocoaPods has incompatibility in different version.

More check:

1. Run `pod repo list`. Then tell me the output. There must be a repo which is named after `master`.
2. Run `pod search MXReact` to check if the `podspec` of `MXReact` is correctly downloaded.

**Comment by li8911255** [comment]
output for
1. master
- Type: git (master)
- URL:  https://github.com/CocoaPods/Specs.git
- Path: /Users/lizhen/.cocoapods/repos/master
2.[!] Unable to find a pod with name, author, summary, or description matching `MXReact`

**Comment by li8911255** [comment]
@CodingForMoney 

output for

1. 

master
- Type: git (master)
- URL:  https://github.com/CocoaPods/Specs.git
- Path: /Users/lizhen/.cocoapods/repos/master

2.

[!] Unable to find a pod with name, author, summary, or description matching `MXReact`

**Comment by CodingForMoney** [comment]
If the master repo is updated , you can find `MXReact` using `search` command.

I'm confused.

Try to upgrade the `CocoaPods`.
