### ISSUE TITLE
关于带返回值的方法调用

### ISSUE THREAD

**Issue by hatjs880328s** [CodingForMoney/axe#6]
使用performselector来调用某个带返回值的方法时，基本数据类型是不支持的。
使用nsinvocation可以，但是如何判定  id类型和基本数据类型呢？ 
因为我们并不知道被调用方法的返回值是 值类型或者是引用类型。
有一个方法是[signature methodReturnType];使用这个方法返回的type与苹果官方文档不一致。
请问作者有什么好的思路解决呢？

**Comment by hatjs880328s** [comment]
目前看到作者调用的方法返回值都放到了闭包中，请问能否直接在方法上返回呢？

**Comment by CodingForMoney** [comment]
Axe框架中，没有用`performSelector` , 不是`targetAction`机制的。而且即使使用targetAction ，也可以通过 `protocol`来声明接口，会指定返回值，直接调用即可，不需要通过`performSelector`和`NSInvocation`.

而动态生成的方法，以及方法返回值、参数的处理，建议你去看一下 JSPatch的代码。
